// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppScan():Promise<Array<any>>;

export function ParseMacho(arg1:string):Promise<Array<any>>;

export function SelectMacho():Promise<string>;
