// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppScan() {
  return window['go']['main']['App']['AppScan']();
}

export function ParseMacho(arg1) {
  return window['go']['main']['App']['ParseMacho'](arg1);
}

export function SelectMacho() {
  return window['go']['main']['App']['SelectMacho']();
}
